============================= test session starts ==============================
platform darwin -- Python 3.8.3, pytest-6.1.2, py-1.9.0, pluggy-0.13.1 -- /Users/meganfrenkel/Workspace/KERMit/server/venv/bin/python
cachedir: .pytest_cache
rootdir: /Users/meganfrenkel/Workspace/KERMit
plugins: mock-3.3.1
collecting ... collected 92 items

server/tests/unit/test_authentication.py::test_authorize_token_missing_header PASSED [  1%]
server/tests/unit/test_authentication.py::test_authorize_token_missing_header2 PASSED [  2%]
server/tests/unit/test_authentication.py::test_authorize_token_malformed_header PASSED [  3%]
server/tests/unit/test_authentication.py::test_authorize_token_validation_error PASSED [  4%]
server/tests/unit/test_authentication.py::test_authorize_token_validation_success_register PASSED [  5%]
server/tests/unit/test_authentication.py::test_authorize_token_validation_success PASSED [  6%]
server/tests/unit/test_authentication.py::test_authorize_token_validation_not_registered PASSED [  7%]
server/tests/unit/test_authentication.py::test_register PASSED           [  8%]
server/tests/unit/test_authentication.py::test_register_missing_info_email PASSED [  9%]
server/tests/unit/test_authentication.py::test_register_missing_info_id PASSED [ 10%]
server/tests/unit/test_authentication.py::test_register_error_googleauth PASSED [ 11%]
server/tests/unit/test_authentication.py::test_register_exception PASSED [ 13%]
server/tests/unit/test_authentication.py::test_register_no_user_yet PASSED [ 14%]
server/tests/unit/test_authentication.py::test_register_exception_db PASSED [ 15%]
server/tests/unit/test_google_auth.py::test_validate_token PASSED        [ 16%]
server/tests/unit/test_google_auth.py::test_get_user_information PASSED  [ 17%]
server/tests/unit/test_player.py::test_save_commit PASSED                [ 18%]
server/tests/unit/test_player.py::test_save PASSED                       [ 19%]
server/tests/unit/test_player.py::test_find_all_puzzles_for_player PASSED [ 20%]
server/tests/unit/test_player.py::test_find_players_for_puzzle PASSED    [ 21%]
server/tests/unit/test_player.py::test_add_player_to_puzzle_already_too_many_players PASSED [ 22%]
server/tests/unit/test_player.py::test_add_player_to_puzzle_player_doesnt_exist PASSED [ 23%]
server/tests/unit/test_player.py::test_add_player_to_puzzle_ok PASSED    [ 25%]
server/tests/unit/test_player.py::test_to_player_to_str PASSED           [ 26%]
server/tests/unit/test_puzzle_exception.py::test_get_message PASSED      [ 27%]
server/tests/unit/test_puzzle_pieces.py::test_find_all_pieces PASSED     [ 28%]
server/tests/unit/test_puzzle_pieces.py::test_get_piece PASSED           [ 29%]
server/tests/unit/test_puzzle_pieces.py::test_get_piece_none PASSED      [ 30%]
server/tests/unit/test_puzzle_pieces.py::test_save_autocommit PASSED     [ 31%]
server/tests/unit/test_puzzle_pieces.py::test_save PASSED                [ 32%]
server/tests/unit/test_puzzle_pieces.py::test_update_success PASSED      [ 33%]
server/tests/unit/test_puzzle_pieces.py::test_update_fail_static PASSED  [ 34%]
server/tests/unit/test_puzzle_pieces.py::test_get_as_str PASSED          [ 35%]
server/tests/unit/test_sudoku_puzzle.py::test_create_sudoku_puzzle_valid_defaults PASSED [ 36%]
server/tests/unit/test_sudoku_puzzle.py::test_create_sudoku_puzzle_valid_specification PASSED [ 38%]
server/tests/unit/test_sudoku_puzzle.py::test_create_sudoku_puzzle_invalid_difficulty_str PASSED [ 39%]
server/tests/unit/test_sudoku_puzzle.py::test_create_sudoku_puzzle_invalid_difficulty_too_low PASSED [ 40%]
server/tests/unit/test_sudoku_puzzle.py::test_create_sudoku_puzzle_invalid_difficulty_too_high PASSED [ 41%]
server/tests/unit/test_sudoku_puzzle.py::test_create_sudoku_puzzle_invalid_size_str PASSED [ 42%]
server/tests/unit/test_sudoku_puzzle.py::test_create_sudoku_puzzle_invalid_size_too_low PASSED [ 43%]
server/tests/unit/test_sudoku_puzzle.py::test_create_sudoku_puzzle_invalid_size_too_high PASSED [ 44%]
server/tests/unit/test_sudoku_puzzle.py::test_set_point_value1 PASSED    [ 45%]
server/tests/unit/test_sudoku_puzzle.py::test_set_point_value2 PASSED    [ 46%]
server/tests/unit/test_sudoku_puzzle.py::test_get_pieces_as_arr_all PASSED [ 47%]
server/tests/unit/test_sudoku_puzzle.py::test_get_pieces_as_arr_static_only PASSED [ 48%]
server/tests/unit/test_sudoku_puzzle.py::test_recreate_original_puzzle PASSED [ 50%]
server/tests/unit/test_sudoku_puzzle.py::test_check_for_completion_null_values PASSED [ 51%]
server/tests/unit/test_sudoku_puzzle.py::test_check_for_completion_complete PASSED [ 52%]
server/tests/unit/test_sudoku_puzzle.py::test_check_for_completion_incorrect_values PASSED [ 53%]
server/tests/unit/test_sudoku_puzzle.py::test_check_discrepancies_none PASSED [ 54%]
server/tests/unit/test_sudoku_puzzle.py::test_check_discrepancies_many_incorrect FAILED [ 55%]
server/tests/unit/test_sudoku_puzzle.py::test_check_discrepancies_incomplete_puzzle PASSED [ 56%]
server/tests/unit/test_sudoku_puzzle.py::test_get_puzzle_none PASSED     [ 57%]
server/tests/unit/test_sudoku_puzzle.py::test_get_puzzle_found PASSED    [ 58%]
server/tests/unit/test_sudoku_puzzle.py::test_save PASSED                [ 59%]
server/tests/unit/test_sudoku_puzzle.py::test_save_autocommit PASSED     [ 60%]
server/tests/unit/test_sudoku_puzzle.py::test_attempt_update_complete_puzzle PASSED [ 61%]
server/tests/unit/test_sudoku_puzzle.py::test_update_invalid_coordinate1 PASSED [ 63%]
server/tests/unit/test_sudoku_puzzle.py::test_update_invalid_coordinate2 FAILED [ 64%]
server/tests/unit/test_sudoku_puzzle.py::test_update_invalid_coordinate3 PASSED [ 65%]
server/tests/unit/test_sudoku_puzzle.py::test_update_invalid_coordinate4 PASSED [ 66%]
server/tests/unit/test_sudoku_puzzle.py::test_update_invalid_value1 PASSED [ 67%]
server/tests/unit/test_sudoku_puzzle.py::test_update_invalid_value2 PASSED [ 68%]
server/tests/unit/test_sudoku_puzzle.py::test_update_valid PASSED        [ 69%]
server/tests/unit/test_sudoku_puzzle.py::test_update_valid_complete_puzzle PASSED [ 70%]
server/tests/unit/test_sudoku_puzzle.py::test_set_puzzle_complete PASSED [ 71%]
server/tests/unit/test_sudoku_puzzle.py::test_as_str PASSED              [ 72%]
server/tests/unit/test_sudoku_resources.py::test_sudoku_to_json PASSED   [ 73%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzles_none PASSED [ 75%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzles_all PASSED [ 76%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzles_create_one_known_exception PASSED [ 77%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzles_create_one_unknown_exception PASSED [ 78%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzles_create_one PASSED [ 79%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzle_none_retrieved PASSED [ 80%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzle_none_associated PASSED [ 81%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzle_found PASSED [ 82%]
server/tests/unit/test_sudoku_resources.py::test_join_sudoku_puzzle_already_joined PASSED [ 83%]
server/tests/unit/test_sudoku_resources.py::test_join_sudoku_puzzle PASSED [ 84%]
server/tests/unit/test_sudoku_resources.py::test_join_sudoku_puzzle_known_exception PASSED [ 85%]
server/tests/unit/test_sudoku_resources.py::test_join_sudoku_puzzle_unknown_exception PASSED [ 86%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzles_add_move_not_associated PASSED [ 88%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzles_add_move PASSED [ 89%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzles_add_move_invalid PASSED [ 90%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzles_add_move_exception PASSED [ 91%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzles_get_solution_not_associated PASSED [ 92%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzles_get_solution_not_associated_2 PASSED [ 93%]
server/tests/unit/test_sudoku_resources.py::test_get_sudoku_puzzles_get_solution PASSED [ 94%]
server/tests/unit/test_user.py::test_create_user PASSED                  [ 95%]
server/tests/unit/test_user.py::test_user_as_str PASSED                  [ 96%]
server/tests/unit/test_user.py::test_user_print PASSED                   [ 97%]
server/tests/unit/test_user.py::test_user_save PASSED                    [ 98%]
server/tests/unit/test_user.py::test_find_by_g_id PASSED                 [100%]

=================================== FAILURES ===================================
___________________ test_check_discrepancies_many_incorrect ____________________

incorrect_puzzle = <Puzzle (transient 140435691064192)>

    def test_check_discrepancies_many_incorrect(incorrect_puzzle):
        """
        A puzzle is not complete if there are pieces that are not valid.
        """
        expected = [
            {'x_coordinate': 1, 'y_coordinate': 1},
            {'x_coordinate': 1, 'y_coordinate': 2},
            {'x_coordinate': 2, 'y_coordinate': 3}
        ]
>       assert expected == incorrect_puzzle.compare_with_solved_board()
E       AssertionError: assert [{'x_coordina...ordinate': 3}] == [{'x_coordina...ordinate': 3}]
E         At index 1 diff: {'x_coordinate': 1, 'y_coordinate': 2} != {'x_coordinate': 0, 'y_coordinate': 2}
E         Full diff:
E           [
E            {'x_coordinate': 1, 'y_coordinate': 1},
E         -  {'x_coordinate': 0, 'y_coordinate': 2},
E         ?                   ^
E         +  {'x_coordinate': 1, 'y_coordinate': 2},...
E         
E         ...Full output truncated (4 lines hidden), use '-vv' to show

server/tests/unit/test_sudoku_puzzle.py:274: AssertionError
_______________________ test_update_invalid_coordinate2 ________________________

self = <sqlalchemy.util._collections.ScopedRegistry object at 0x7fb9bb07cf70>

    def __call__(self):
        key = self.scopefunc()
        try:
>           return self.registry[key]
E           KeyError: 4685680064

server/venv/lib/python3.8/site-packages/sqlalchemy/util/_collections.py:1020: KeyError

During handling of the above exception, another exception occurred:

monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7fb9bb852e80>
incomplete_puzzle = <Puzzle (transient 140435691744608)>

    def test_update_invalid_coordinate2(monkeypatch, incomplete_puzzle):
        """
        Users should not be able to make moves to coordinates outside the range of the puzzle.
        """
        with pytest.raises(PuzzleException) as pe:
>           incomplete_puzzle.update(1, 1, 1)

server/tests/unit/test_sudoku_puzzle.py:379: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
server/models/sudoku_puzzle.py:167: in update
    db.session.commit()
server/venv/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py:163: in do
    return getattr(self.registry(), name)(*args, **kwargs)
server/venv/lib/python3.8/site-packages/sqlalchemy/util/_collections.py:1022: in __call__
    return self.registry.setdefault(key, self.createfunc())
server/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py:3300: in __call__
    return self.class_(**local_kw)
server/venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py:138: in __init__
    bind = options.pop('bind', None) or db.engine
server/venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py:943: in engine
    return self.get_engine()
server/venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py:962: in get_engine
    return connector.get_engine()
server/venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py:555: in get_engine
    options = self.get_options(sa_url, echo)
server/venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py:570: in get_options
    self._sa.apply_driver_hacks(self._app, sa_url, options)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <[AttributeError("'NoneType' object has no attribute 'drivername'") raised in repr()] SQLAlchemy object at 0x7fb9bb07c580>
app = <Flask 'server.server'>, sa_url = None, options = {}

    def apply_driver_hacks(self, app, sa_url, options):
        """This method is called before engine creation and used to inject
        driver specific hacks into the options.  The `options` parameter is
        a dictionary of keyword arguments that will then be used to call
        the :func:`sqlalchemy.create_engine` function.
    
        The default implementation provides some saner defaults for things
        like pool sizes for MySQL and sqlite.  Also it injects the setting of
        `SQLALCHEMY_NATIVE_UNICODE`.
        """
>       if sa_url.drivername.startswith('mysql'):
E       AttributeError: 'NoneType' object has no attribute 'drivername'

server/venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py:883: AttributeError
=========================== short test summary info ============================
FAILED server/tests/unit/test_sudoku_puzzle.py::test_check_discrepancies_many_incorrect
FAILED server/tests/unit/test_sudoku_puzzle.py::test_update_invalid_coordinate2
========================= 2 failed, 90 passed in 0.88s =========================
